### ISSUE TITLE
ModuleNotFoundError: No module named 'Cryptodome' when trying to use rostopic pub in launchfile

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/mros1_reasoner#8]
I have tried to create a mock diagnostics using rostopic pub ni the mros1_reasoner launch file, but I get the following error:
```
Traceback (most recent call last):
  File "/home/chcorbato/rospy3_melodic/src/ros_comm/rostopic/scripts/rostopic", line 35, in <module>
    rostopic.rostopicmain()
  File "<string>", line 2118, in rostopicmain
  File "/home/chcorbato/rospy3_melodic/devel/lib/python3/dist-packages/rosbag/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 33, in <module>
  File "/home/chcorbato/rospy3_melodic/src/ros_comm/rosbag/src/rosbag/bag.py", line 53, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'
```

This is the code that causes it when added in the launchfile:
```
 <node name="fake_m_diagnostics" pkg="rostopic" type="rostopic" args="pub /metacontrol_diagnostics DiagnosticArray.msg
    '{[status: {level: 1, name: '', message: '', values: []}]
    }' -r 2"/>
```

For the moment, I will use a launch file in the `abb_cheops_ws` for this implementation of `mock_metacontrol_diagnostic` with `rostopic`

**Comment by chcorbato** [comment]
Update: I get an error `ModuleNotFoundError: No module named 'rostopic'` when trying to use `rostopic` in the workspace with Melodic build from sources with Python3 support.
I guess I am missing some ROS utils in that ws.

**Comment by chcorbato** [comment]
This was a problem with the sourcing of overlay workspaces.
should be solved following updated instructions in branch [`mvp`](https://github.com/rosin-project/mros1_reasoner/tree/mvp)
